# Generated by Django 4.2 on 2023-05-30 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('crew_id', models.AutoField(primary_key=True, serialize=False)),
                ('crew_name', models.CharField(max_length=50, verbose_name="crew's name ")),
                ('crew_pic', models.ImageField(upload_to='images/crew/')),
            ],
        ),
        migrations.CreateModel(
            name='Island',
            fields=[
                ('island_id', models.AutoField(primary_key=True, serialize=False)),
                ('island_name', models.CharField(max_length=50, verbose_name="island's name ")),
                ('island_region', models.CharField(max_length=50, verbose_name="island's location ")),
                ('island_pic', models.ImageField(upload_to='images/island/')),
            ],
        ),
        migrations.CreateModel(
            name='Has',
            fields=[
                ('has_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=0, max_digits=4, verbose_name='quantity ')),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crews.crew')),
                ('island', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crews.island')),
            ],
            options={
                'unique_together': {('crew', 'island')},
            },
        ),
    ]
