# Generated by Django 4.2 on 2023-05-31 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='has',
            name='quantity',
        ),
    ]
