# Generated by Django 4.2 on 2023-06-07 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crews', '0002_remove_has_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.AutoField(primary_key=True, serialize=False)),
                ('region_name', models.CharField(max_length=50, verbose_name="region's name ")),
                ('region_pic', models.ImageField(upload_to='images/region/')),
            ],
        ),
    ]
