# Generated by Django 4.2 on 2023-06-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crews', '0003_region_alter_island_island_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='island',
            name='island_region',
            field=models.CharField(max_length=50, verbose_name='tqt   '),
        ),
    ]
