# Generated by Django 4.2 on 2023-06-07 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crews', '0005_alter_island_island_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='island',
            name='island_region',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='crews.region'),
        ),
    ]
