# Generated by Django 4.2 on 2023-06-07 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crews', '0006_alter_island_island_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='island',
            name='island_region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crews.region'),
            preserve_default=False,
        ),
    ]
